#*********************************************************
#  Platform dependent rules and defines...
#*********************************************************

CC = gcc
#CFLAGS = -dn

ARCH = solaris
LDFLAGS = -lnsl -lsocket -lcurses -lucb -lm

include ../sor.mk
