#*********************************************************
#  Platform dependent rules and defines...
#*********************************************************

CC     = cc
#CFLAGS = -dn

ARCH = linux
#LDFLAGS = -lnsl -lsocket -L/usr/ucblib -lcurses -lucb -lm
LDFLAGS = -libverbs
include ../is.mk
