#*********************************************************
#  Platform dependent rules and defines...
#*********************************************************

ARCH = linux
#LDFLAGS = -lnsl -lsocket -L/usr/ucblib -lcurses -lucb -lm
LDFLAGS = -lm -libverbs -lrdmacm
include ../lu.mk
