#*********************************************************
#  Platform dependent rules and defines...
#*********************************************************

CC = cc
#CFLAGS = -dn

ARCH = linux
#LDFLAGS = -lnsl -lsocket -lcurses -lucb -lm
LDFLAGS = -lpthread -libverbs -lrdmacm
include ../pi.mk
