#*********************************************************
#  Platform dependent rules and defines...
#*********************************************************

CC = gcc
CFLAGS += -g

ARCH = linux
#LDFLAGS = -lm -lbsd 
LDFLAGS = -lpthread -libverbs -lrdmacm
include ../sor.mk
