#*********************************************************
#  Platform dependent rules and defines...
#*********************************************************

CC = cc
CFLAGS = -Wunused-result

ARCH = linux
#LDFLAGS = -lnsl -lcurses
LDFLAGS = 

include ../tsp.mk
