#*********************************************************
#  Platform dependent rules and defines...
#*********************************************************

CC = gcc

ARCH = linux
#LDFLAGS = -lnsl -lsocket -lcurses  -lucb
LDFLAGS = -lpthread -libverbs -lrdmacm
include ../mm.mk
