#*********************************************************
#  Platform dependent rules and defines...
#*********************************************************

ARCH = linux
ARCH_FLAGS = -DLINUX -DOSTAT
CPPFLAGS = -O2 


include ../Makefile.common
