#*********************************************************
#  Platform dependent rules and defines...
#*********************************************************

ARCH = linux
ARCH_FLAGS = -DLINUX
CPPFLAGS = -O0


include ../lib.mk
