#*********************************************************
#  Platform dependent rules and defines...
#*********************************************************

CC = cc
#CFLAGS = -dn

ARCH = linux
#LDFLAGS = -lnsl -lcurses -lm
LDFLAGS = -lm -lpthread -libverbs -lrdmacm

include ../water.mk
