#*********************************************************
#  Platform dependent rules and defines...
#*********************************************************

CC = cc

ARCH = linux
#LDFLAGS = -lnsl -lcurses -lm
LDFLAGS = -lm

include ../water.mk
