#*********************************************************
#  Platform dependent rules and defines...
#*********************************************************

CC = cc
#CFLAGS = -dn

ARCH = linux
LDFLAGS = -lnsl -lsocket -lcurses -lucb -lm

include ../Makefile.common
