#*********************************************************
#  Platform dependent rules and defines...
#*********************************************************

CC = cc
CFLAGS += -DLINUX

ARCH = linux
LDFLAGS = -lm -lpthread -libverbs -lrdmacm
include ../ep.mk