#*********************************************************
#  Platform dependent rules and defines...
#*********************************************************

CC = cc
CFLAGS += -DLINUX

ARCH = linux
LDFLAGS = -lm
include ../ep.mk